#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GDG_SP.Droid.Resource", IsApplication=true)]

namespace GDG_SP.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::GDG_SP.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int facebook = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_facebook = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_google = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_instagram = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_mail = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_notification = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_people = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_rsvp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_send = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_share = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_site = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_twitter = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_youtube = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int os_bgimage_notif_bgimage = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int os_bgimage_notif_body = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int os_bgimage_notif_title = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int onesignal_bgimage_notif_layout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
