//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDG_SP.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDG_SP.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDG-SP.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps.aloogle.net/meetup/backend/.
        /// </summary>
        internal static string BackendUrl {
            get {
                return ResourceManager.GetString("BackendUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF008bf8.
        /// </summary>
        internal static string ColorPrimary {
            get {
                return ResourceManager.GetString("ColorPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organizers@gdgsp.org.
        /// </summary>
        internal static string ContactMail {
            get {
                return ResourceManager.GetString("ContactMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.com/DevFestBrasil.
        /// </summary>
        internal static string FacebookUrl {
            get {
                return ResourceManager.GetString("FacebookUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.com/+GDGspOrg.
        /// </summary>
        internal static string GooglePlusUrl {
            get {
                return ResourceManager.GetString("GooglePlusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instagram.com/gdgsp.
        /// </summary>
        internal static string InstagramUrl {
            get {
                return ResourceManager.GetString("InstagramUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDG-SP.
        /// </summary>
        internal static string MeetupId {
            get {
                return ResourceManager.GetString("MeetupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.com/channel/UC8yjEZ7-hroweXUgjPMwXNQ/videos?shelf_id=2&amp;amp;view=2&amp;amp;live_view=503&amp;amp;sort=dd.
        /// </summary>
        internal static string OldMeetupsUrl {
            get {
                return ResourceManager.GetString("OldMeetupsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f5131d6c-de7a-45c3-bb07-764879be97d3.
        /// </summary>
        internal static string OneSignalAppId {
            get {
                return ResourceManager.GetString("OneSignalAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gdgsp.org.
        /// </summary>
        internal static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.com/GDGSaoPaulo.
        /// </summary>
        internal static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.com/channel/UCs_F2tnlETe3dt8W86aWnOA.
        /// </summary>
        internal static string YouTubeUrl {
            get {
                return ResourceManager.GetString("YouTubeUrl", resourceCulture);
            }
        }
    }
}
